### ISSUE TITLE
Segmentation classes description not available

### ISSUE THREAD

**Issue by AkhilaPhenomx** [fepegar/highresnet#36]
I'm reading the code and the paper (highres3dnet_brain_parcellation) and I can't find what anatomical parcellation corresponds to each class.
It would be great if there was a description for each class.

**Comment by fepegar** [comment]
Here it is: https://github.com/fepegar/highresnet/blob/master/GIFNiftyNet.ctbl

**Comment by AkhilaPhenomx** [comment]
This helps! Thank you so much. 
But, color values for both left and right segmentations are same.

`8 Right-Accumbens-Area 48 176 96 255
9 Left-Accumbens-Area 48 176 96 255`
