### ISSUE TITLE
highresnet sometimes outputs a value of 20 or 21 which are not in GIFNiftyNet.ctbl

### ISSUE THREAD

**Issue by paul-reiners** [fepegar/highresnet#37]
* highresnet version: 0.10.2
* Python version: 3.8.3
* Operating System: Linux

### Description

highresnet sometimes outputs a value of 20 or 21 neither of which are in GIFNiftyNet.ctbl.

What brain region do 20 and 21 stand for?

### What I Did

Ran highresnet on a NIFTI file.

**Comment by fepegar** [comment]
I don't have an answer for this.

Maybe @wyli or @res191 can help.

**Comment by wyli** [comment]
do they refer to the 19th/20th (zero-indexed) line of GIFNiftyNet.ctbl ? which means `23 Right-Hippocampus` and `24 Left-Hippocampus`.

**Comment by fepegar** [comment]
> do they refer to the 19th/20th (zero-indexed) line of GIFNiftyNet.ctbl ? which means 23 Right-Hippocampus and 24 Left-Hippocampus.

I don't think so. The hippocampus seems fine.

I ran the example in the README of this repo and got no voxels labeled as 20. These are the ones labeled as 21:

![Screenshot](https://user-images.githubusercontent.com/12688084/114106573-f23d9200-98c6-11eb-8ae6-e8c43b3ba33e.png)

Maybe some of the labels marked in GIF as "non-brain" or something similar got remapped to 20 and 21.

**Comment by fepegar** [comment]
It's probably "non-ventricular CSF".

Anyway, @paul-reiners I think you can safely ignore the labels that are not present in the color table and consider them background.

**Comment by wyli** [comment]
alright... waded through the 2017 backup files maybe they mean `20 Right-Cerebral-Exterior` `21 Left-Cerebral-Exterior`

**Comment by fepegar** [comment]
Thanks for the archeology! It does sound like those structures can be safely ignored then. Is that ok, @paul-reiners?

**Comment by paul-reiners** [comment]
Yes, that's okay.  Thanks for taking the time to look into this.
