### ISSUE TITLE
Hi，Highresnet is suitable for the processed hcp 1200 3d Mri.nii.gz？

### ISSUE THREAD

**Issue by NewboySoCool** [fepegar/highresnet#41]

**Comment by fepegar** [comment]
Hi, @FreshmanMa. I assume you're talking about the Human Connectome Project. I think it would work, yes.

**Comment by NewboySoCool** [comment]
> Hi, @FreshmanMa. I assume you're talking about the Human Connectome Project. I think it would work, yes.

It's suitable for preprocessed HCP 1200 MRI.nii.gz？ I can't get a correct segmentation result.
![image](https://github.com/fepegar/highresnet/assets/93995539/119fa4b7-98cb-44e3-9905-3215e5c16e20)

**Comment by NewboySoCool** [comment]
![image](https://github.com/fepegar/highresnet/assets/93995539/f81c594f-4486-4409-b111-ff2667e60a60)
531536.nii.gz is like this
