### ISSUE TITLE
There is a promble about segmentation on unprocessed HCP (320×320×256) ?

### ISSUE THREAD

**Issue by NewboySoCool** [fepegar/highresnet#42]
![为啥我是27](https://github.com/fepegar/highresnet/assets/93995539/37b5e3d8-2d2b-41b3-8588-7af582fdf314)
why is 27? not 36

**Comment by fepegar** [comment]
Sorry, I need more context to help you.

**Comment by NewboySoCool** [comment]
> Sorry, I need more context to help you.
Thanks， I'm using deepgif to segement on preprocessed HCP 1200 MRI.nii.gz data?

**Comment by NewboySoCool** [comment]
![image](https://github.com/fepegar/highresnet/assets/93995539/975e31f7-bd38-4139-bb2a-cd6294ff2f78)

**Comment by NewboySoCool** [comment]
So，deepgif  is not suitable for preprocessed HCP 1200 MRI.nii.gz？

**Comment by NewboySoCool** [comment]
> So，deepgif is not suitable for preprocessed HCP 1200 MRI.nii.gz？

Is suitable for this kind of mri data？
![image](https://github.com/fepegar/highresnet/assets/93995539/4f0f9969-0ab4-46bf-9d24-a86773017cc5)

**Comment by fepegar** [comment]
It should be. Have you tried?

**Comment by NewboySoCool** [comment]
> It should be. Have you tried?
Yeah，I had tried  with deepgif. It doesn't work on my mri.nii.gz?  I have no idea about how to do. I feel a little sad, can you give me some advice or provide other method to segmentation about my data？
![image](https://github.com/fepegar/highresnet/assets/93995539/ce70afc9-9312-49dc-b85f-5f71ab34c59e)

**Comment by fepegar** [comment]
Can you please clearly explain what you tried, what you expected and what happened? And share a minimal working example I can reproduce?

**Comment by NewboySoCool** [comment]
> Can you please clearly explain what you tried, what you expected and what happened? And share a minimal working example I can reproduce?

OK，Thanks, I wanna use HighRes3DNet to do segmentation task on my 3d mri.nii.gz after skull-stripped, and get the picture like the following img  which is  included in the thesis, "MRI Super-Resolution with GAN and 3D Multi-Level DenseNet: Smaller, Faster, and Better".  But, in this paper, their data is original data, is not preprocessed.
I provide one data, 531536.nii.gz data.  I use `deefgif  531536.nii.gz`   to run, you can have try. 
![image](https://github.com/fepegar/highresnet/assets/93995539/34ce42ca-8f6e-43cd-8d37-80cc7875ae82)

[531536.nii.gz](https://github.com/fepegar/highresnet/files/12266630/531536.nii.gz)

**Comment by fepegar** [comment]
Here's a reproducible example using your data: https://colab.research.google.com/drive/12Z5QnWlGuShMnKlnM_HWmNdHNdmxoK2r?usp=sharing.
It doesn't seem to generate good results. This is probably because the network wasn't trained on skull-stripped images.

I recommend using more modern and robust tools such as [SynthSeg](https://surfer.nmr.mgh.harvard.edu/fswiki/SynthSeg).

**Comment by NewboySoCool** [comment]
> 

Ok, thanks very much, I'll try the SynthSeg! It's nice of you, thanks again!

**Comment by fepegar** [comment]
You're welcome!
